---
show-messages-onjoin: true
force-hub: false
enable-hub-message: true
force-spawn: false
enable-spawn-message: true
enable-aliases: true
teleport-on-death: 1
hub-server:
  enabled: false
  name: External Server
  host: 127.0.0.1
  port: 19132
hub:
  world: LB
  X: 254.411100
  "Y": 100.816000
  Z: 268.560700
  Yaw: 273.165939
  Pitch: 38.625595
...
