# Config file for VoteReward by LDX.
#
# Official VoteReward Server List Directory:
# http://votereward.mcpe.me/?p=lists
#
# Config Variables:
#   {USERNAME} ... The username of the player who voted. ....... Commands and message.
#   {NICKNAME} ... The display name of the player who voted. ... Commands and message.
#   {X} .......... The X coordinate of the player. ............. Commands only.
#   {Y} .......... The Y coordinate of the player. ............. Commands only.
#   {Y1} ......... The Y coordinate of the player plus 1. ...... Commands only.
#   {Z} .......... The Z coordinate of the player. ............. Commands only.

# EssentialsPE style color codes can be used in the message and commands.

# Message to broadcast to the server when a player votes.
Message: "§l§b[§a VOTE §b ]§6 Thanh niên §e{NICKNAME}§6 vừa vote nhận được:§a 1 Point, 5000 Yên,..."

# List of items to give players when they vote. Format: ID:Damage:Amount
Items:
  - "264:0:5"
  - "265:0:3"
  - "364:0:5"

# List of commands to execute when a player votes.
Commands:
  - "particle portal {X} {Y1} {Z} 2 2 2 10000"
  - "givepoint {USERNAME} 1"
  - "givemoney {USERNAME} 5000"
